		<!-- Flot -->
	    <script src="{url_data}/js/plugins/flot/jquery.flot.js"></script>
	    <script src="{url_data}/js/plugins/flot/jquery.flot.tooltip.min.js"></script>
	    <script src="{url_data}/js/plugins/flot/jquery.flot.spline.js"></script>
	    <script src="{url_data}/js/plugins/flot/jquery.flot.resize.js"></script>
	    <script src="{url_data}/js/plugins/flot/jquery.flot.pie.js"></script>
	    <script src="{url_data}/js/plugins/flot/jquery.flot.symbol.js"></script>
	    <script src="{url_data}/js/plugins/flot/jquery.flot.time.js"></script>

	    <!-- Peity -->
	    <script src="{url_data}/js/plugins/peity/jquery.peity.min.js"></script>
	    <script src="{url_data}/js/demo/peity-demo.js"></script>

	    <!-- Custom and plugin javascript -->
	    <script src="{url_data}/js/inspinia.js"></script>
	    <script src="{url_data}/js/plugins/pace/pace.min.js"></script>

	    <!-- jQuery UI -->
	    <script src="{url_data}/js/plugins/jquery-ui/jquery-ui.min.js"></script>

	    <!-- Jvectormap -->
	    <script src="{url_data}/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
	    <script src="{url_data}/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>

	    <!-- EayPIE -->
	    <script src="{url_data}/js/plugins/easypiechart/jquery.easypiechart.js"></script>

	    <!-- Sparkline -->
	    <script src="{url_data}/js/plugins/sparkline/jquery.sparkline.min.js"></script>

	    <!-- Sparkline demo data  -->
	    <script src="{url_data}/js/demo/sparkline-demo.js"></script>
	</body>
</html>