{header|include}

	<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>All games in database</h2>
            <ol class="breadcrumb">
                <li>
                    <strong>Games</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <div class="wrapper wrapper-content">
    	<div class="row">
			<div class="col-lg-12">
				<div class="ibox float-e-marigns">
					<div class="ibox-title">
						<h5>All games in database</h5>
						<div class="ibox-tools">
	                        <a class="collapse-link">
	                            <i class="fa fa-chevron-up"></i>
	                        </a>
	                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
	                            <i class="fa fa-wrench"></i>
	                        </a>
	                        <ul class="dropdown-menu dropdown-user">
	                            <li><a href="#">Config option 1</a>
	                            </li>
	                            <li><a href="#">Config option 2</a>
	                            </li>
	                        </ul>
	                        <a class="close-link">
	                            <i class="fa fa-times"></i>
	                        </a>
	                    </div>
					</div>
					<div class="ibox-content">
						<table class="table table-striped table-hover table-bordered dataTables_wrapper form-inline" id="all_games_datatables">
							<thead>
								<th>Name</th>
								<th>Developer</th>
								<th>Actual GamePlays</th>
								<th>Actual Rating</th>
								<th>Total Ratings</th>
								<th>Actual Favorites</th>
							</thead>

							<tbody>

								{games|foreach}

									<tr>
										<td><a href="app/games/{name}">{name}</a></td>
										<td>{developer}</td>
										<td>{actual_gameplays_count}</td>
										<td>{actual_rating_count}</td>
										<td>{total_ratings_count}</td>
										<td>{actual_favorites_count}</td>
									</tr>

								{games|/foreach}

							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
    </div>

	<!-- Data Tables -->
    <script src="{url_data}/js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="{url_data}/js/plugins/dataTables/dataTables.bootstrap.js"></script>
    <script src="{url_data}/js/plugins/dataTables/dataTables.responsive.js"></script>
    <script src="{url_data}/js/plugins/dataTables/dataTables.tableTools.min.js"></script>

	<script type="text/javascript">

		$(document).ready(function() {
			$('#all_games_datatables').DataTable({
                responsive: true
            });
		});

	</script>

{footer|include}