<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>KG-Rating - Statistics of your games!</title>

    <meta name="keywords" content="Kongregate, statistics, gamestats, graphs, kg-rating" />
    <meta name="description" content="This web-application serves for viewing statistics of games, which are uploaded on Kongregate." />
    <meta name="robots" content="index,follow" />
    <meta name="author" content="Dreaw.cz" />

    <link rel="icon" type="image/png" href="{url}/favicon.png" />

    <link href="{url_data}/css/bootstrap.min.css" rel="stylesheet">
    <link href="{url_data}/font-awesome/css/font-awesome.css" rel="stylesheet">

    <!-- Morris -->
    <link href="{url_data}/css/plugins/morris/morris-0.4.3.min.css" rel="stylesheet">

    <!-- Gritter -->
    <link href="{url_data}/js/plugins/gritter/jquery.gritter.css" rel="stylesheet">

    <!-- Data Tables -->
    <link href="{url_data}/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
    <link href="{url_data}/css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
    <link href="{url_data}/css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">

    <!-- Homepage -->
    <link href="{url_data}/css/home.css" rel="stylesheet">

    <link href="{url_data}/css/animate.css" rel="stylesheet">
    <link href="{url_data}/css/style.css" rel="stylesheet">

    <!-- Require scripts on load -->
    <script src="{url_data}/js/jquery-2.1.1.js"></script>
    <script src="{url_data}/js/bootstrap.min.js"></script>
    <script src="{url_data}/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="{url_data}/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
</head>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67767089-1', 'auto');
  ga('send', 'pageview');

</script>

<body class="fixed-sidebar top-navigation">
    <div id="wrapper">
        <div id="page-wrapper" class="gray-bg">