{header|include}

    <div class="middle-box text-center loginscreen   animated fadeInDown">
        <div>
            <div>

                <h1 class="logo-name">KG</h1>

            </div>
            <h3>Register to KG-Rating</h3>
            <p>Create account to see it in action.</p>

            {getMessage}

            <form class="m-t" role="form" action="" method="post">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Developer" name="dev" required="" value="{developer_value}">
                </div>

                <div class="form-group">
                    <input type="email" class="form-control" placeholder="Email" name="email" required="" value="{email_value}">
                </div>

                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Password" name="pw" required="">
                </div>

                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Verify password" name="verify_pw" required="">
                </div>

                <input type="hidden" name="dreaw_token" value="{getToken}" />

                <button type="submit" class="btn btn-primary block full-width m-b" name="register_submit">Register</button>

                <p class="text-muted text-center"><small>Already have an account?</small></p>
                <a class="btn btn-sm btn-white btn-block" href="/login">Login</a>
            </form>
            <p class="m-t"> <small>KG-Rating.com</small> </p>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="{url_data}js/jquery-2.1.1.js"></script>
    <script src="{url_data}js/bootstrap.min.js"></script>
    <!-- iCheck -->
    <script src="{url_data}js/plugins/iCheck/icheck.min.js"></script>
    <script>
        $(document).ready(function(){
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });
        });
    </script>

{footer|include}