{header|include}

	<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Changelog</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/app">Home</a>
                </li>

                <li>
                    <strong>Changelog</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <br  />

    {getMessage}


    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox">
                    <div class="ibox-title">
                        <h5>Changelog</h5>
                    </div>

                    <div class="ibox-content">
                        <div class="row">

                            {logs|foreach}

                                <div class="col-lg-4">
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            {date}
                                        </div>
                                        <div class="panel-body bbc">
                                            <p>{text}</p>
                                        </div>

                                    </div>
                                </div>

                            {logs|/foreach}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Data Tables -->
    <script src="https://www.kg-rating.com/common/libs/template/js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="https://www.kg-rating.com/common/libs/template/js/plugins/dataTables/dataTables.bootstrap.js"></script>
    <script src="https://www.kg-rating.com/common/libs/template/js/plugins/dataTables/dataTables.responsive.js"></script>
    <script src="https://www.kg-rating.com/common/libs/template/js/plugins/dataTables/dataTables.tableTools.min.js"></script>

    <script src="{url}/common/libs/bbcode/xbbcode.js"></script>

    <script type="text/javascript">

        $(document).ready(function() {
            $('#data_tables').DataTable();

            for (var i = $('.bbc').length - 1; i >= 0; i--) {
                var result = XBBCODE.process({
                    text: $('.bbc:eq(' + i + ')').text(),
                    removeMisalignedTags: false,
                    addInLineBreaks: true
                });

                $('.bbc:eq(' + i + ')').html(result.html);
            };
        });

    </script>


{footer|include}