{header|include}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>DevTracker</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/app">Home</a>
                </li>

                <li>
                    <strong>DevTracker</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <br />

    {getMessage}

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox">
                    <div class="ibox-title">
                        <h5>Issue list</h5>
                        <div class="ibox-tools">
                            <a href="/app/dev-tracker/add/" class="btn btn-primary btn-xs">Add new issue</a>
                        </div>
                    </div>

                    <div class="ibox-content">
                        <table class="table table-hover issue-tracker table-striped table-bordered dataTables_wrapper" id="data_tables">
                            <thead>
                                <tr>
                                    <th>Category</th>
                                    <th>Text</th>
                                    <th>Status</th>
                                    <th>User</th>
                                    <th>Attachment</th>
                                    <th>Date</th>
                                </tr>
                            </thead>

                            <tbody>

                                {issues|foreach}

                                    <tr>
                                        <td>
                                            <span class="label label-{category_color}">{category}</span>
                                        </td>
                                        <td class="issue-info">
                                            <small>{text}</small>
                                        </td>
                                        <td class="right">
                                            <small>{status}</small>
                                        </td>
                                        <td align="right">
                                            {developer_name}
                                        </td>
                                        <td align="right">
                                            {file_1|if=""replace="-"else="<a href='{file_1}'>Attachment</a>"}
                                        </td>
                                        <td align="right">
                                            {date}
                                        </td>
                                    </tr>

                                {issues|/foreach}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Data Tables -->
    <script src="{url_data}/js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="{url_data}/js/plugins/dataTables/dataTables.bootstrap.js"></script>
    <script src="{url_data}/js/plugins/dataTables/dataTables.responsive.js"></script>
    <script src="{url_data}/js/plugins/dataTables/dataTables.tableTools.min.js"></script>

    <script type="text/javascript">

        $(document).ready(function() {
            $('#data_tables').DataTable();
        });

    </script>

{footer|include}