{header|include}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Add a custom game</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/app">Home</a>
                </li>
                <li class="active">
                    <strong>Add game</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <div class="wrapper wrapper-content">
        {getMessage}
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Add your game</h5>
                    </div>
                    <div class="ibox-content">
                        <form class="form-horizontal" action="" method="POST">
                            <p>Add your game to the database to collect its statistics.</p>
                            <div class="form-group">
                                <label class="col-lg-2 control-label">Game URL</label>
                                <div class="col-lg-10">
                                    <input type="text" name="game_url" placeholder="http://www.kongregate.com/games/developer/game" class="form-control">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button class="btn btn-sm btn-primary" type="submit" name="game_submit">Add game to the database!</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="wrapper wrapper-content">
        <div class="modal inmodal" id="changelog_modal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content animated bounceInRight">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                        <i class="fa fa-laptop modal-icon"></i>
                        <h4 class="modal-title">Changelog</h4>
                        <small class="font-bold">What has been changed in our app?</small>
                    </div>
                    <div class="modal-body" style="background: #fff !important">
                        <p id="changelog_text">
                        </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{url}/common/libs/bbcode/xbbcode.js"></script>

    <script>
        $(document).ready(function() {
            /* AJAX -> changelog */
                $.ajax({
                    url: '',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        'action': 'changelog'
                    }
                }).always(function(data) {
                    if (data['view'] == 'true') {
                        $("#changelog_text").text(data['text']);
                        $("#changelog_modal").modal();

                        for (var i = $('#changelog_text').length - 1; i >= 0; i--) {
                            var result = XBBCODE.process({
                                text: $('#changelog_text:eq(' + i + ')').text(),
                                removeMisalignedTags: false,
                                addInLineBreaks: true
                            });

                            $('#changelog_text:eq(' + i + ')').html(result.html);
                        };
                    }
                });

            /* /AJAX -> changelog */
        });
    </script>
{footer|include}