{header|include}

	<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>All games in database</h2>
            <ol class="breadcrumb">
            	<li>
                    <a href="/app">Home</a>
                </li>

                <li>
                    <strong>Games</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <br  />
    {getMessage}

    <div class="wrapper wrapper-content">
    	<div class="row">
			<div class="col-lg-12">
				<div class="ibox float-e-marigns">
					<div class="ibox-title">
						<h5>All games in database</h5>
					</div>
					<div class="ibox-content">
						<table class="table table-striped table-hover table-bordered dataTables_wrapper form-inline" id="all_games_datatables">
							<thead>
								<th>Name</th>
								<th>Developer</th>
								<th>Gameplays</th>
								<th>Rating</th>
								<th>Number of ratings</th>
								<th>Favorites</th>
							</thead>

							<tbody>

								{games|foreach}

									<tr>
										<td><a href="games/{code_represent}">{name}</a></td>
										<td>{developer}</td>
										<td>{actual_gameplays_count}</td>
										<td>{actual_rating_count}</td>
										<td>{total_ratings_count}</td>
										<td>{actual_favorites_count}</td>
									</tr>

								{games|/foreach}

							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
    </div>

	<!-- Data Tables -->
    <script src="{url_data}/js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="{url_data}/js/plugins/dataTables/dataTables.bootstrap.js"></script>
    <script src="{url_data}/js/plugins/dataTables/dataTables.responsive.js"></script>
    <script src="{url_data}/js/plugins/dataTables/dataTables.tableTools.min.js"></script>

	<script type="text/javascript">

		$(document).ready(function() {
			$('#all_games_datatables').DataTable({
                responsive: true,
                "order": []
            });
		});

	</script>

{footer|include}