<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{title}</title>

    <link rel="icon" type="image/png" href="{url}/favicon.png" />

    <link href="{url_data}/css/bootstrap.min.css" rel="stylesheet">
    <link href="{url_data}/font-awesome/css/font-awesome.css" rel="stylesheet">

    <!-- Morris -->
    <link href="{url_data}/css/plugins/morris/morris-0.4.3.min.css" rel="stylesheet">

    <!-- Gritter -->
    <link href="{url_data}/js/plugins/gritter/jquery.gritter.css" rel="stylesheet">

    <!-- Data Tables -->
    <link href="{url_data}/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
    <link href="{url_data}/css/plugins/dataTables/dataTables.responsive.css" rel="stylesheet">
    <link href="{url_data}/css/plugins/dataTables/dataTables.tableTools.min.css" rel="stylesheet">

    <link href="{url_data}/css/animate.css" rel="stylesheet">
    <link href="{url_data}/css/style.css" rel="stylesheet">

    <!-- Date Picker -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

    <!-- Require scripts on load -->
    <script src="{url_data}/js/jquery-2.1.1.js"></script>
    <script src="{url_data}/js/bootstrap.min.js"></script>
    <script src="{url_data}/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="{url_data}/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <script src="{url_data}/js/plugins/daterangepicker/daterangepicker.js"></script>
</head>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67767089-1', 'auto');
  ga('send', 'pageview');

</script>

<body class="fixed-sidebar">
    <div id="wrapper">
        <nav class="navbar-default navbar-static-side" role="navigation">
            <ul class="nav" id="side-menu">
                <li class="nav-header">
                    <div class="dropdown profile-element">
                        <span>
                            <img alt="image" class="img-circle" src="/app/secure-img/profile_image">
                        </span>
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear">
                                <span class="block m-t-xs">
                                    <a href="/app/profile/{uid_logged}"><strong class="font-bold">{uid_logged}</strong></a>
                                </span>

                                <span class="text-muted text-xs block">User type: {perm|if="0"replace="Admin"else="Developer"}</span>
                            </span>
                        </a>
                    </div>
                    <div class="logo-element">
                        KG+
                    </div>
                </li>

                <li>
                    <a href="/app">
                        <i class="fa fa-home"></i>
                        <span class="nav-label">Home</span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <i class="fa fa-gamepad"></i>
                        <span class="nav-label">Games</span>
                        <span class="fa arrow"></span>
                    </a>

                    <ul class="nav nav-second-level collapse">
                        <li>
                            <a href="/app/myGames">My games</a>
                        </li>
                        <li>
                            <a href="/app/games">All games</a>
                        </li>
                        <li>
                            <a href="/app/gameAdd">Add game</a>
                        </li>
                    </ul>
                </li>


                <li>
                    <a href="/app/developers">
                        <i class="fa fa-users"></i>
                        <span class="nav-label">Developers</span>
                    </a>
                </li>

                <li>
                    <a href="/app/changeLog">
                        <i class="fa fa-bell"></i>
                        <span class="nav-label">Changelog</span>
                    </a>
                </li>

                <li>
                    <a href="/app/profile/{uid_logged}">
                        <i class="fa fa-th-large"></i>
                        <span class="nav-label">Profile</span>
                    </a>
                </li>

                <li>
                    <a href="#">
                        <i class="fa fa-envelope"></i>
                        <span class="nav-label">Dev tracker</span>
                        <span class="fa arrow"></span>
                    </a>

                    <ul class="nav nav-second-level collapse">
                        <li><a href="/app/dev-tracker/add">Add Issue</a></li>
                        <li><a href="/app/dev-tracker/view">View Tracker</a></li>
                    </ul>
                </li>
            </ul>

        </div><div class="slimScrollBar" style="width: 7px; position: absolute; top: 0px; opacity: 0.4; display: none; border-radius: 7px; z-index: 99; right: 1px; height: 130.812993854258px; background: rgb(0, 0, 0);"></div><div class="slimScrollRail" style="width: 7px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; opacity: 0.9; z-index: 90; right: 1px; background: rgb(51, 51, 51);"></div></div>
    </nav>
        <div id="page-wrapper" class="gray-bg">
            <div class="row border-bottom">
                <nav class="navbar" role="navigation" style="margin-bottom: 0">
                    <ul class="nav navbar-top-links navbar-left">
                    </ul>

                    <ul class="nav navbar-top-links navbar-right">
                        <li>
                            <a href="/logOut">
                                <i class="fa fa-sign-out"></i> Log out
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>