{header|include}
	<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Homepage</h2>
            <ol class="breadcrumb">
            	<li>
                    <strong>Home</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">
        </div>
    </div>

    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Sorry.</h5>
                    </div>
                    <div class="ibox-content">
                        <p>This page is not finished yet.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Data Tables -->
    <script src="{url_data}/js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="{url_data}/js/plugins/dataTables/dataTables.bootstrap.js"></script>
    <script src="{url_data}/js/plugins/dataTables/dataTables.responsive.js"></script>
    <script src="{url_data}/js/plugins/dataTables/dataTables.tableTools.min.js"></script>

{footer|include}