{header|include}

	<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>My profile</h2>
            <ol class="breadcrumb">
            	<li>
                    <a href="/app/">Home</a>
                </li>
                <li>
                	<strong>Profile</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <br  />{getMessage}

    <div class="wrapper wrapper-content">
    	<div class="row animated fadeInRight">
            <div class="col-md-4">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Profile Detail</h5>
                    </div>

                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-md-2">
                                <img alt="image" class="img-responsive" src="/app/secure-img/profile_image" />
                            </div>

                            <div class="col-md-10">
                                <h4><strong>{uid_logged}</strong></h4>
                                <h5>
                                    About me
                                </h5>
                                <p id="description_text">{description|if=""replace="Write your description.."}</p>
                                <textarea class="form-control" id="description_area" style="display:none" name="message_text">{description}</textarea>
                            </div>
                        </div>

                        <hr />

                        <div class="row">
                            <div class="col-md-12">
                                <div class="user-button">
                                    <div class="row">
                                        <form id="sending_form" action="" method="POST" enctype="multipart/form-data">
                                            <div class="col-md-6">
                                                <input type="file" class="btn btn-primary btn-sm btn-block" name="image_field" value="Select image" />
                                            </div>
                                            <div class="col-md-6">
                                                <button class="btn btn-sm btn-primary btn-sm btn-block" type="submit" name="set_profile"><i class="fa fa-picture-o"></i>&nbsp;&nbsp;Set profile image</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        $("#description_text").click(function() {
            $("#description_text").css("display", "none");
            $("#description_area").css("display", "inline");
        });

        $("#description_area").change(function() {
            $.ajax({
                url: '',
                type: 'POST',
                dataType: 'json',
                data: {
                    'action' : 'change_description',
                    'text' : $("#description_area").val()
                }
            }).always(function(data) {
                $("#description_area").css("display", "none");
                $("#description_text").css("display", "inline");
                $("#description_text").text(data);
            });   
        });
    </script>

{footer|include}