{header|include}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>DevTracker</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/app">Home</a>
                </li>

                <li>
                    <a href="/app/devTracker/view">DevTracker</a>
                </li>

                <li>
                    <strong>Add issue</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <br  />
    {getMessage}

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-6">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Add issue</h5>
                    </div>

                    <div class="ibox-content">
                        <form enctype="multipart/form-data" class="form-horizontal" method="post" action="">
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Category</label>

                                <div class="col-sm-10">
                                    <select class="form-control m-b" name="category">
                                        <option value="bug">bug</option>
                                        <option value="note">note</option>
                                        <option value="idea">idea</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-2 control-label">Attachment (optional)</label>

                                <div class="col-sm-10">
                                    <input type="file" value="" id ="file_input" name="ufile"  />
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-2 control-label">Message</label>

                                <div class="col-sm-10">
                                    <textarea class="form-control" placeholder="Write message..." name="message_text"></textarea>
                                </div>
                            </div>

                            <button class="btn btn-sm btn-primary pull-center m-t-n-xs" type="submit" name="tracker_add_submit"><strong>Add issue</strong></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{footer|include}